### PR TITLE
Update Langfuse filter pipeline

### LINKED ISSUE #2: I'd suggest to use the updated Langfuse filter pipeline contributed to open-webui/pipelines
Great work on this example!

I'd suggest to update the pipeline to this one: https://github.com/open-webui/pipelines/blob/main/examples/filters/langfuse_filter_pipeline.py

New features
- correct token amounts
- use of email as userId in Langfuse
- correct tracking of sessionId in Langfuse

### PR DESCRIPTION
**Pull request by marcklingen**
Fixes #2

Update `example/langfuse_filter_pipeline.py` to use the updated Langfuse filter pipeline.

### CODE REVIEW

**Comment by karaketir16** [comment]
Great, thanks. 

Is there any change needed in the README?

**Comment by marcklingen** [comment]
thank you for reviewing this so quickly.

you could refer to this guide which includes screenshots in our docs: https://langfuse.com/docs/integrations/openwebui

**Comment by karaketir16** [comment]
I prefer to keep `pk` and `sk` as an example.

Thanks for your contribution.

**Comment by karaketir16** [comment]
@marcklingen Somehow, I managed to commit directly to your repository without a PR: [commit link](https://github.com/marcklingen/openwebui-langfuse/commit/92c430cae23e1e9246657745f23d55a1e54df091). Is this an intended feature, or could it be a bug of GitHub? Could you possibly open a dummy pull request so I can test if this happens again?

**Pull request merged**
